[workspace]
authors = ["sapetnioc <sapetnioc@users.noreply.github.com>"]
channels = ["conda-forge"]
name = "blender-conda"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
rattler-build = "*"
rattler-index = "*"
